import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import logo from "../pictures/logo-with-name.png";
import Link from "next/link";
import { getUser } from "@/utils/auth/user";
import { ProfileButton } from "../components/profile-button-dropdown"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const authorized = getUser() != null;

export const metadata: Metadata = {
  title: "sojourn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="w-full max-w-md flex justify-between items-center">
          <Link href="/home" className="absolute top-4 left-4">
            <Image src={logo} alt="logo" width={128} height={128} />
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
